name: "CI - Test Templates"
on:
  pull_request:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      templates: ${{ steps.filter.outputs.changes }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - uses: jannekem/run-python-script-action@v1
        id: generate-changes
        with:
          script: |
            import os
            for folder in os.listdir('src'):
                print(f"{folder}:")
                print(f"  - '**/{folder}/**'")
                print(f"  - '.github/workflows/test-pr.yaml'")

      - name: Paths Filter
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            ${{ steps.generate-changes.outputs.stdout }}

  test:
    needs: [detect-changes]
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        templates: ${{ fromJSON(needs.detect-changes.outputs.templates) }}
    steps:
      - uses: actions/checkout@v4

      - name: Smoke test for '${{ matrix.templates }}'
        id: smoke_test
        uses: ./.github/actions/smoke-test
        with:
          template: "${{ matrix.templates }}"
